version: "3.1"

services:
  mothership:
    build:
      context: ./Mothership/
      dockerfile: ./Mothership/Dockerfile
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      replicas: 1

networks:
  external:
